site_name: R4A APIs
nav:
  - Home: index.md
  - Utilities:
    - Messages: messages.md
    - Memory: memory.md
    - Conditions: conditions.md
    - Enumerations: enums.md
  - Robot API: robotapi.md
  - Cloud API: cloudapi.md
  - Generic API: genericapi.md
  - FSM-like applications: nodes.md
  - Examples: examples.md
