site_name: R4A APIs
nav:
  - Home: index.md
  - Utilities:
    - Exceptions: exceptions.md
    - Messages: messages.md
    - Memory: memory.md
    - Conditions: conditions.md
    - Enumerations: enums.md
  - Robot API:
    - General: robotapi.md
    - Enabling resources: resources.md
    - Speakers API: speakers.md
    - Microphone API: microphone.md
    - Camera API: camera.md
    - Touch screen API: touchscreen.md
    - LEDs API: leds.md
    - Buttons API: buttons.md
    - Environmental API: env.md
    - Encoders API: encoders.md
    - Time-of-flight API: tof.md
    - Sonars API: sonars.md
    - Infrared API: irs.md
    - Pan-tilt API: pantilt.md
    - Body motion API: motion.md
    - IMU API: imu.md
  - Cloud API:
    - General: cloudapi.md
    - Age detection API: cloud_age_detection.md
    - Dominant color API: cloud_dominant_color.md
    - Face detection API: cloud_face_detection.md
    - Gender detection API: cloud_gender_detection.md
    - Language detection API: cloud_language_detection.md
    - Motion detection API: cloud_motion_detection.md
    - OCR API: cloud_ocr.md
    - Sound detection API: cloud_sound_detection.md
    - Speech-2-text API: cloud_speech_to_text.md
    - Sentiment detection API: cloud_sentiment_detection.md
    - Translate API: cloud_translate_from_audio.md
    - Weather API: cloud_weather.md
    - Cloud QR/Barcode API: cloud_qr_barcode.md
  - Generic API:
    - General: genericapi.md
    - Sleep API: generic_sleep.md
    - Counter API: generic_counter.md
  - FSM-like applications: nodes.md
  - Examples: examples.md
